name: Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable

      - uses: Swatinem/rust-cache@v1
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install wasm-bindgen-cli

      - name: Install and Build
        run: |
          cargo build --target wasm32-unknown-unknown
          wasm-bindgen ./target/wasm32-unknown-unknown/debug/rlox_lib.wasm --out-dir ./pages/rlox

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: pages # The folder the action should deploy.
